modLoader="javafml"
loaderVersion="[36,)"
license="Custom"
# issueTrackerURL=""

[[mods]]
modId="achristmasmod"
version="1.0.0"
displayName="A Christmas Mod"
# updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/a-christmas-mod-forge"
# logoFile=""
authors="Willatendo"
description='''
A Forge mod filled with lots of holiday based features!
'''

[[dependencies.achristmasmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.achristmasmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.achristmasmod]]
    modId="tyrannotitanlib"
    mandatory=true
    versionRange="[v1.2.3,)"
    ordering="NONE"
    side="BOTH"