modLoader="javafml"
loaderVersion="[43,)"
license="https://github.com/willatendo/Willatendos-Licensing"
issueTrackerURL="https://github.com/willatendo/A-Christmas-Mod/issues"

[[mods]]
modId="achristmasmod" 
version="1.0.0"
displayName="A Christmas Mod"
# updateJSONURL=""
# displayURL=""
# logoFile="" 
authors="Willatendo"
description='''
A mod about holidays in December and how they change in each country!
'''

[[dependencies.achristmasmod]] 
    modId="forge" 
    mandatory=true 
    versionRange="[43,)" 
    ordering="NONE"
    side="BOTH"
    
[[dependencies.achristmasmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"